apiVersion: v1
kind: Template
metadata:
  name: parity
  labels:
    apps: parity
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: parity
  spec:
    tags:
    - name: "${PARITY_VERSION}"
      from:
        kind: DockerImage
        name: docker.io/parity/parity:stable
      annotations:
        description: Parity is Ethcore's initial fully-featured, Ethereum-compatible, blockchain implementation.
        tags: blockchain,ethereum
        version: "${PARITY_VERSION}"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: parity
  spec:
    replicas: 1
    selector:
      app: parity
      deploymentconfig: parity
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: parity
          deploymentconfig: parity
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: parity
          ports:
          - containerPort: 8180
            protocol: TCP
          - containerPort: 8545
            protocol: TCP
          - containerPort: 8546
            protocol: TCP
          # - containerPort: 30303
          #   protocol: TCP
          # - containerPort: 30303
          #   protocol: UDP
          command: ["/parity/parity"]
          args:
          - --config
          - /opt/parity/conf/config.toml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: parity-config
            mountPath: /opt/parity/conf
          - name: parity-data
            mountPath: /opt/parity/data
        volumes:
        - name: parity-config
          configMap:
            name: parity
        - name: parity-data
          persistentVolumeClaim:
            claimName: parity-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - parity
        from:
          kind: ImageStreamTag
          name: parity:${PARITY_VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: parity
  spec:
    ports:
    - name: 8180-tcp
      port: 8180
      protocol: TCP
      targetPort: 8180
    - name: 8545-tcp
      port: 8545
      protocol: TCP
      targetPort: 8545
    - name: 8546-tcp
      port: 8546
      protocol: TCP
      targetPort: 8546
    selector:
      deploymentconfig: parity
      app: parity
    type: ClusterIP
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: parity-data
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: parity
  data:
    config.toml: |-
      [parity]
      chain = "/opt/parity/conf/spec.json"
      base_path = "/opt/parity/data/parity0"

      [account]
      password = ["/opt/parity/conf/node.pwd"]

      [ui]
      port = 8180
      hosts = ["all"]

      [network]
      port = 30300

      [rpc]
      port = 8545
      hosts = ["all"]
      apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
      cors = "all"

      [websockets]
      port = 8546
      hosts = ["all"]
      origins = ["all"]

      [ipc]
      disable = true

      [mining]
      engine_signer = "0x00bd138abd70e2f00903268f3db08f2d25677c9e"
      reseal_on_txs = "none"
      usd_per_tx = "0"
    spec.json: |-
      {
        "name": "MyPrivateChainDemo",
        "engine": {
          "authorityRound": {
            "params": {
              "stepDuration": "5",
              "validators": { "list": [] }
            }
          }
        },
        "params": {
          "gasLimitBoundDivisor": "0x400",
          "maximumExtraDataSize": "0x20",
          "minGasLimit": "0x1388",
          "networkID": "0x2323"
        },
        "genesis": {
          "seal": {
            "authorityRound": {
              "step": "0x0",
              "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
          },
          "difficulty": "0x20000",
          "gasLimit": "0x5B8D80"
        },
        "accounts": {
          "0x0000000000000000000000000000000000000001": {
            "balance": "1",
            "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } }
          },
          "0x0000000000000000000000000000000000000002": {
            "balance": "1",
            "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } }
          },
          "0x0000000000000000000000000000000000000003": {
            "balance": "1",
            "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } }
          },
          "0x0000000000000000000000000000000000000004": {
            "balance": "1",
            "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } }
          }
        }
      }
    node.pwd: |-
      node0
parameters:
- name: PARITY_VERSION
  displayName: Parity Image Tag
  description: 'Version of the Parity container image. Check the available version https://hub.docker.com/r/parity/parity/tags/'
  value: "stable"
  required: true

